### ISSUE TITLE
Error parsing .gradle file

### ISSUE THREAD

**Issue by apetesh** [ninetwozero/gradle-to-js#13]
Hi,

Parsing a .build file containing the following text:
```
def coverageTaskAndroidJob = task("coverageTaskAndroidJob",
        dependsOn: ':android-job:createCovAndroidTestCoverageReport') {

    def dep1 = tasks.getByPath(':android-job:clean')

    def target = tasks.getByPath(':android-job:createCovAndroidTestCoverageReport')

    target.dependsOn dep1
    group = "Coverage"
    description 'Runs coverage for android-job'
}

def coverageTaskVolley = task("coverageTaskVolley",
        dependsOn: ':volley:createCovCoverageReport') {

    def dep1 = tasks.getByPath(':volley:clean')
    def dep2 = tasks.getByPath(':volley:testCovUnitTest')

    def target = tasks.getByPath(':volley:createCovCoverageReport')

    target.dependsOn dep1
    target.dependsOn dep2
    group = "Coverage"
    description 'Runs coverage for volley'
}
```
causes the following error:

```
TypeError: Cannot assign to read only property '0' of object '[object String]'
    at assignKey (<project>/node_modules/deep-assign/index.js:28:13)
    at assign (<project>/node_modules/deep-assign/index.js:43:7)
    at assignKey (<project>/node_modules/deep-assign/index.js:30:15)
    at assign (<project>/node_modules/deep-assign/index.js:43:7)
    at deepAssign (<project>/node_modules/deep-assign/index.js:64:5)
    at deepParse (<project>/node_modules/gradle-to-js/lib/parser.js:160:29)
    at Readable.<anonymous> (<project>/node_modules/gradle-to-js/lib/parser.js:623:13)
    at Readable.emit (events.js:160:13)
    at Readable.read (_stream_readable.js:482:10)
    at flow (_stream_readable.js:853:34)
    at emitReadable_ (_stream_readable.js:521:3)
    at process._tickCallback (internal/process/next_tick.js:152:19)
```

**Comment by karllindmark** [comment]
Hi Asaf!

Thanks for the report!

What would the expected result be? 😊

Best regards,
Karl Lindmark

**Comment by apetesh** [comment]
Hi Karl,

The expected result should be:
1.  The object representation of the blocks
2. Not crashing when parsing a file which contains this chunk of text.

Thanks for the quick reply!

**Comment by matthiasthomas** [comment]
Hey guys, 

I went through the same issue today. I can privately send you the culprit file if you need. I'm also going to investigate on my side, I'll keep you updated.

**Comment by karllindmark** [comment]
Hey Matthias!

If you could shoot me an email with the culprit, that would be great. I
need to get own my computer up to speed since I was using my previous
employer's up until April. 😀

**Comment by karllindmark** [comment]
@apetesh: Could you provide me with a snippet with the expected result? I'm setting up a test case here locally and would like your input on it. :-)

**Comment by matthiasthomas** [comment]
Hi @karllindmark ! Here's the file!
I didn't really have time to look into it, but deep-assign is deprecated and seems to be the issue so it might be a good idea to switch to merge-options or some other module.

Thanks,

[mat.zip](https://github.com/ninetwozero/gradle-to-js/files/1938865/mat.zip)

**Comment by karllindmark** [comment]
Thanks Matthias!

I'll add looking into alternative libraries to my TODO before pushing a new
version. As of last night I'm starting to understand where this problem is
occurring in terms of the parser code too, so hopefully I'll have a fix out
real soon. ☺️

**Comment by karllindmark** [comment]
Hey guys! So, I have a possible solution for this issue in #14 - would you care to take a look? @apetesh @matthiasthomas 🤝

**Comment by dilipkumar2k6** [comment]
I tested for this issue `13` by using branch `feature/add-support-for-multiline-closures` but this issue still persist. I still see same issue.
